apiVersion: v1
kind: Service
metadata:
  name: {{ template "stolon.keeper.fullname" . }}
  labels:
    app: {{ template "stolon.keeper.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
    component: keeper
spec:
  {{ if .Values.keeper.serviceType }}
  type: {{ .Values.keeper.serviceType }}
  {{ end }}
  ports:
    - port: {{ .Values.ports.externalPort }}
      targetPort: {{ .Values.ports.internalPort }}
  selector:
    app: {{ template "stolon.keeper.fullname" . }}
    component: keeper
